import {
  Body,
  Controller,
  Post,
  BadRequestException,
  UseGuards,
  Req,
  Res,
  HttpCode,
  HttpStatus,
} from '@nestjs/common';
import { Response } from 'express';
import {
  ApiBearerAuth,
  ApiOperation,
  ApiResponse,
  ApiTags,
} from '@nestjs/swagger';
import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import { QueryService } from './query.service';

interface AuthReq extends Request {
  user: { id: number; email: string };
}

interface QueryDto {
  question: string;
  session_id?: string;   // UUID generated by the frontend per "New Chat" click
}

@ApiTags('Query')
@ApiBearerAuth()
@UseGuards(JwtAuthGuard)
@Controller()
export class QueryController {
  constructor(private readonly queryService: QueryService) {}

  // ── Regular (non-streaming) response ──────────────────────────────────────
  @Post('query')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({ summary: 'Ask a question — returns full answer at once' })
  @ApiResponse({ status: 200 })
  async query(@Body() body: QueryDto, @Req() req: AuthReq) {
    if (!body?.question?.trim()) {
      throw new BadRequestException('question field is required');
    }
    const sessionId = body.session_id ?? 'default';
    return this.queryService.answer(body.question.trim(), req.user.id, sessionId);
  }

  // ── Streaming response via Server-Sent Events (SSE) ───────────────────────
  // Uses POST so the JWT can be passed in the Authorization header.
  // The frontend uses fetch() with a ReadableStream reader.
  //
  // SSE format: each event is "data: <json>\n\n"
  // Chunk event: { "chunk": "some text" }
  // Done event:  { "done": true, "sources": [...] }
  @Post('query/stream')
  @ApiOperation({
    summary: 'Ask a question — streams the answer word-by-word (SSE)',
  })
  async stream(
    @Body() body: QueryDto,
    @Req() req: AuthReq,
    @Res() res: Response,
  ) {
    if (!body?.question?.trim()) {
      throw new BadRequestException('question field is required');
    }

    const sessionId = body.session_id ?? 'default';

    // Set SSE response headers
    res.setHeader('Content-Type', 'text/event-stream');
    res.setHeader('Cache-Control', 'no-cache');
    res.setHeader('Connection', 'keep-alive');
    res.setHeader('X-Accel-Buffering', 'no'); // disable nginx buffering
    res.flushHeaders();

    try {
      for await (const event of this.queryService.streamAnswer(
        body.question.trim(),
        req.user.id,
        sessionId,
      )) {
        if (event.type === 'chunk') {
          res.write(`data: ${JSON.stringify({ chunk: event.text })}\n\n`);
        } else {
          // Final event — includes sources so the client can display citations
          res.write(`data: ${JSON.stringify({ done: true, sources: event.sources })}\n\n`);
        }
      }
    } catch (err) {
      res.write(`data: ${JSON.stringify({ error: 'Stream failed' })}\n\n`);
    } finally {
      res.end();
    }
  }
}
